;;   -*- lexical-binding: t; -*-
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-colon
	c-electric-lt-gt
	c-electric-paren
	c-electric-semi&comma
	end-of-visual-line
	indent-for-tab-command
	kill-region
	kill-visual-line
	org-beginning-of-line
	org-delete-char
	sp-mark-sexp
	))

(setq mc/cmds-to-run-once
      '(
	c-electric-delete-forward
	eshell-send-input
	org-self-insert-command
	pixel-scroll-precision
	pixel-scroll-start-momentum
	))
