;;   -*- lexical-binding: t; -*-
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-colon
	c-electric-lt-gt
	c-electric-paren
	c-electric-semi&comma
	embark-act
	embrace-change
	end-of-visual-line
	indent-for-tab-command
	kill-region
	kill-visual-line
	org-beginning-of-line
	org-ctrl-c-ctrl-c
	org-cycle
	org-delete-char
	org-end-of-line
	org-force-self-insert
	org-self-insert-command
	sp-mark-sexp
	sp-remove-active-pair-overlay
	))

(setq mc/cmds-to-run-once
      '(
	pixel-scroll-precision
	pixel-scroll-start-momentum
	toggle-input-method
	))
